# ETAPA 1: Build (Compilación)
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# 1. Copiamos el archivo de proyecto (MinisterioCorban.csproj)
COPY ["MinisterioCorban.csproj", "."]

# 2. Restauramos las dependencias
RUN dotnet restore "./MinisterioCorban.csproj"

# 3. Copiamos todo el resto del código
COPY . .

# 4. Publicamos la aplicación en modo Release
RUN dotnet publish "MinisterioCorban.csproj" -c Release -o /app/publish /p:UseAppHost=false

# ETAPA 2: Runtime (Imagen final ligera)
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app

# --- CONFIGURACIÓN PARA RENDER ---
# Forzamos explícitamente a la app a usar el puerto 8080
ENV ASPNETCORE_HTTP_PORTS=8080
EXPOSE 8080
# ---------------------------------

# 5. Traemos los archivos compilados de la etapa anterior
COPY --from=build /app/publish .

# 6. Punto de entrada
ENTRYPOINT ["dotnet", "MinisterioCorban.dll"]